spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password: gTYù=(iA5?&_/
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop